  name: unit tests
  on:
    - push
  jobs:
    run-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
        - name: Maven tests
          run: mvn --batch-mode surefire-report:report verify
        - name: Publish test results
          uses: actions/upload-artifact@v1
          with:
            name: surefire-report.html
            path: ./target/site/surefire-report.html